<?php
/**
 * This file is part of Glugox.
 *
 * (c) Glugox <glugox@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
?>
<?php $_category = $block->getCategory() ?>
<?php $_pdfProductCount = $this->getEstimatePrintProductsOnCategory($_category); ?>
<?php if ($_pdfProductCount && $block->canDisplayOnCategory($_category)): ?>
<a title="<?php echo __('Will print %1 product(s) to PDF', $_pdfProductCount); ?>" href="<?php /* @escapeNotVerified */ echo $this->helper('Glugox\PDF\Helper\Data')->getCategoryPrintPdfUrl($_category) ?>"
       class="action link pdf"><span><?php /* @escapeNotVerified */ echo __('PDF') ?></span></a>
<?php endif; ?>