<?php
/**
 * This file is part of Glugox.
 *
 * (c) Glugox <glugox@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
// @codingStandardsIgnoreFile
?>
<script>
    require([
        "jquery",
        'Magento_Ui/js/modal/confirm',
        "jquery/ui",
        "glugoxPDF"
    ], function ($, Confirm) {
        /**
         * Confirm dialog for delete pdf action
         */
        $(function () {
            $('div#pdfGrid').on('click', 'button#delete', function (e) {

                new Confirm({
                    title: 'Are you sure?',
                    content: "Are you sure you want to delete this pdf? You can't undo this action.",
                    actions: {
                        confirm: function () {
                            window.location.href = $(e.target).data('url');
                        }
                    }
                });
                e.stopPropagation();
            });
        });

    });
</script>

<div id="glugox-pdf-popup-container" style="display: none;"></div>